version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network

  web:
    build:
      context: .
    container_name: challenge_3_web
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017  # Define MongoDB URL here

networks:
  app_network:
    driver: bridge

