version: "3.9"

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  webdb:
    build:
      context: ./webdb
    container_name: webdb
    ports:
      - "5001:5000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    networks:
      - app-network


  webnodb:
    build:
      context: ./webnodb
    container_name: webnodb
    ports:
      - "5002:5000"  # Expose app 2 on port 5002
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./NGINX.conf:/etc/nginx/nginx.conf  # Mount custom NGINX configuration
    depends_on:
      - webdb
      - webnodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge