apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: endiaye
spec:
  type: ClusterIP
  selector:
    app: webnodb
  ports:
  - port: 80  # Service port
    targetPort: 5000  # Pod port