apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: endiaye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb
        image: faliloundiaye/webnodb:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "0.1"  # 1/10 CPU
            memory: "100Mi"  # 100 MB RAM
          limits:
            cpu: "0.2"  # 1/5 CPU
            memory: "200Mi"  # 200 MB RAM